[package]
name = "redoxide"
version = "0.2.0"
edition = "2021"
rust-version = "1.88"

[[bin]]
name = "redoxide"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "sync", "time"] }
bollard = "0.18"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.103"
